### ISSUE TITLE
PV unsafe access 

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#112]
(APP VERSION: 44, LINE: undefined, SOURCE: /detail.html) jQuery.Deferred exception: Cannot read property 'hourlyCost' of null,TypeError: Cannot read property 'hourlyCost' of null
at Object.<anonymous> (http://localhost:9090/helper.js:607:74)
at Function.each (https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js:2:2623)
at Object.exports.aggregateCostModelByField (http://localhost:9090/helper.js:546:9)
at printByCluster (http://localhost:9090/detail.html:474:32)
at http://localhost:9090/detail.html:1418:9

**Comment by dwbrown2** [comment]
@AjayTripathy is this now fixed?

**Comment by AjayTripathy** [comment]
Yes, this is now fixed.
