### ISSUE TITLE
Can't find discount function in certain jobs

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#117]
This appears to only happen in certain deployment states.

```
Warning: No platform host found at http://kubecost-cost-analyzer.kubecost.svc.cluster.local:9001
jQuery.Deferred exception: getRemoteDiscount is not defined ReferenceError: getRemoteDiscount is not defined
    at Object.<anonymous> (/queries.js:71:26)
    at Function.each (/node/node_modules/jquery/dist/jquery.js:367:19)
    at Array.<anonymous> (/queries.js:64:11)
    at mightThrow (/node/node_modules/jquery/dist/jquery.js:3557:29)
    at Window.process (/node/node_modules/jquery/dist/jquery.js:3625:12)
    at Timeout.callback [as _onTimeout] (/node/node_modules/jsdom/lib/jsdom/browser/Window.js:665:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) undefined
```

**Comment by dwbrown2** [comment]
Fixed in v1.45 which was released last night!
