### ISSUE TITLE
Not seeing any metrics in most of the dashboards

### ISSUE THREAD

**Issue by immusk** [kubecost/cost-analyzer-helm-chart#164]
Hi Team,

I have setup kubecost with the latest release tar file.

After the UI is up, I don't see that most of the grafana dashboards shows empty data.

Can you please help how to debug these, and I even see this empty board on the UI too
<img width="718" alt="Screen Shot 2019-12-05 at 8 45 21 AM" src="https://user-images.githubusercontent.com/8833971/70201108-a1021900-173b-11ea-8972-678ea42ba655.png">
<img width="730" alt="Screen Shot 2019-12-05 at 8 45 26 AM" src="https://user-images.githubusercontent.com/8833971/70201109-a19aaf80-173b-11ea-8ec0-f462d8ff315c.png">

**Comment by immusk** [comment]
seeing the below error in `cost-analyzer-checks` pods

`Starting...
Send alert to
fe url
Warning: unable to measure cluster memory usage
jQuery.Deferred exception: log is not defined ReferenceError: log is not defined
    at Object.<anonymous> (/issues.js:151:15)
    at mightThrow (/node/node_modules/jquery/dist/jquery.js:3557:29)
    at Window.process (/node/node_modules/jquery/dist/jquery.js:3625:12)
    at Timeout.callback [as _onTimeout] (/node/node_modules/jsdom/lib/jsdom/browser/Window.js:665:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) undefined
jQuery.Deferred exception: Cannot read property 'values' of undefined TypeError: Cannot read property 'values' of undefined
    at Object.<anonymous> (/issues.js:21:35)
    at mightThrow (/node/node_modules/jquery/dist/jquery.js:3557:29)
    at Window.process (/node/node_modules/jquery/dist/jquery.js:3625:12)
    at Timeout.callback [as _onTimeout] (/node/node_modules/jsdom/lib/jsdom/browser/Window.js:665:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) undefined
{ text: 'ALERT: You are requesting 143.89000000000001% of your total cluster CPU. Details at /health.html?id=highClusterCpuRequestUtilization&threshold=0.8' }
{ text: 'ALERT: You have 3 pod(s) in a crash loop for 10m Details at /health.html?id=crashLooping&' }
{ text: 'ALERT: You have 4 pod(s) pending for the last 10m Details at /health.html?id=pendingPods&' }
{ text: 'ALERT: You have 1 deployments(s) with replicas below 50% Details at /health.html?id=lowReplicas&threshold=0.5' }
Warning: No platform host found at http://kubecost-cost-analyzer.kubecost.svc.cluster.local:9001
Error: Uncaught [TypeError: Cannot read property 'totalCost' of undefined]
    at reportException (/node/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at innerInvokeEventListeners (/node/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:331:9)
    at invokeEventListeners (/node/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:266:3)
    at XMLHttpRequestEventTargetImpl._dispatch (/node/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:212:11)
    at fireAnEvent (/node/node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)
    at Request.properties.client.on (/node/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:935:7)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/node/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30) TypeError: Cannot read property 'totalCost' of undefined
    at Object.success (/issues.js:49:48)
    at fire (/node/node_modules/jquery/dist/jquery.js:3291:31)
    at Object.fireWith [as resolveWith] (/node/node_modules/jquery/dist/jquery.js:3421:7)
    at done (/node/node_modules/jquery/dist/jquery.js:9533:14)
    at XMLHttpRequest.<anonymous> (/node/node_modules/jquery/dist/jquery.js:9785:9)
    at XMLHttpRequest.el.addEventListener.event (/node/node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:33:32)
    at innerInvokeEventListeners (/node/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:315:27)
    at invokeEventListeners (/node/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:266:3)
    at XMLHttpRequestEventTargetImpl._dispatch (/node/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:212:11)
    at fireAnEvent (/node/node_modules/jsdom/lib/jsdom/living/helpers/events.js:17:36)`

**Comment by immusk** [comment]
I missed updating the main thing.. 
we are not using the GKE, we have our own setup of Kubernetes running on EC2 instances.

**Comment by dwbrown2** [comment]
Hi @immusk, thanks for reporting! A couple quick questions:

1. Can you confirm what version you are running?
2. Can you share any developer console logs on the page where this is occurring?
3. Can you share the logs from the cost-model container in the cost-analyzer pod?

**Comment by immusk** [comment]
Hi @dwbrown2 

1. I am using the `v1.49.0` of kubecost
2. developer console logs attached the log file.
3. logs from the cost-model container in the cost-analyzer pod - attached the log file

few more things:
I am not using the prometheus that comes up with kubecost, I am using our's already setup prometheus and I have already added these configs to ours Prometheus for scraping the data
 extraScrapeConfigs: |
    - job_name: kubecost
      honor_labels: true
      scrape_interval: 1m
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      dns_sd_configs:
        - names:
        - {{ template "cost-analyzer.serviceName" . }}
        type: 'A'
        port: 9003
    - job_name: kubecost-networking
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
      # Scrape only the the targets matching the following metadata
        - source_labels: [__meta_kubernetes_pod_label_app]
          action: keep
          regex:  {{ template "cost-analyzer.networkCostsName" . }}
[qa4-test-cost-analyzer.xxxx.com-1575894779136.log](https://github.com/kubecost/cost-analyzer-helm-chart/files/3939626/qa4-test-cost-analyzer.xxxx.com-1575894779136.log)
[cost-model-logs.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/3939634/cost-model-logs.txt)

I see that most of the grafana dashboards are having no data on it.

please help to overcome these issues.

**Comment by dwbrown2** [comment]
Hi @immusk, we only officially support custom Prometheus with an upgrade because there are a lot of external variables that can impact this. I'm happy to do my best to talk through your situation if that would be helpful though. Reach out team@kubecost.com if you think we can help!

**Comment by immusk** [comment]
Hi @dwbrown2 

I think you misunderstood my question.
`our own Prometheus` - means official Prometheus only.
can you check the logs shared in the above comment and suggest how to over come these issues.

**Comment by immusk** [comment]
<img width="718" alt="Screen Shot 2019-12-05 at 8 45 21 AM" src="https://user-images.githubusercontent.com/8833971/70532212-95b84e80-1b7c-11ea-8901-e75402fbf75f.png">
only this dashboard is not loading up, and seeing this below in console logs

`{code: 500, status: "error", data: null, message: "Not enough data available in the selected time range"}
code: 500
data: null
message: "Not enough data available in the selected time range"
status: "error"
__proto__: Object`

**Comment by dwbrown2** [comment]
Hi @immusk, sorry for the miscommunication. When I said custom prometheus, I meant not using our bundled prometheus, i.e. a prometheus outside of our deployment. Unfortunately this isn't supported without an upgrade. Again, happy to discuss later this week if you're interested. Live troubleshooting is often required because there are number of things that could be impacting.

**Comment by immusk** [comment]
Hi @dwbrown2 

yes, that would be great if we can connect and debug it, I work in IST hours, let me know you availability so that we can connect together and troubleshoot it.

Thanks 😄

**Comment by dwbrown2** [comment]
Cool, email team@kubecost.com or drop your contact info and we can find a time. I can be available tonight or tomorrow morning your time.

**Comment by dwbrown2** [comment]
Closing issue because this was resolved, please feel free to reopen!

**Comment by infa-ssaurabh** [comment]
I am also facing the same issue, what was the solution for this?

**Comment by dwbrown2** [comment]
@infa-ssaurabh I believe this scenario was a prometheus relabel rule. Want to send us a [bug report](http://docs.kubecost.com/bug-report) and we can take a look for you? 

The other troubleshooting steps would be 1) reviewing Prometheus diagnostic in settings and 2) making sure there are not warnings/errors in your browser's developer console.
