### ISSUE TITLE
"right-sizing" UI page broken

### ISSUE THREAD

**Issue by yurii-kryvosheia** [kubecost/cost-analyzer-helm-chart#2037]
---
# For reproducible bugs, please provide the following

**Describe the bug**  
New UI shows blank page at "Request right-sizing recommendations".

**To Reproduce**  
The bug is not persistent. For some namespaces in the same cluster the page loads fine.
Go to "Allocations" -> choose namespace -> click on any controller

**Expected behavior**  
Recomendations page loads
![image](https://user-images.githubusercontent.com/114397894/223771029-c3663593-b783-4be6-ad63-22bd59aca355.png)

**Collect logs (please complete the following information):**
Console error:
```
instrument.ts:124 TypeError: Cannot read properties of null (reading 'cpu')
    at Object.accessorFn (ResultsTable.tsx:105:55)
    at Object.getValue (row.ts:48:43)
    at Object.getValue (cell.ts:35:25)
    at cell (ResultsTable.tsx:107:46)
    at Si (react-dom.production.min.js:167:137)
    at Sc (react-dom.production.min.js:290:337)
    at xl (react-dom.production.min.js:280:389)
    at yl (react-dom.production.min.js:280:320)
    at vl (react-dom.production.min.js:280:180)
    at il (react-dom.production.min.js:271:88)
    at al (react-dom.production.min.js:268:429)
    at j (scheduler.production.min.js:13:203)
    at MessagePort.A (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
```
**Version**
1.100.2

**Comment by AjayTripathy** [comment]
cc @nealormsbee @michaelmdresser 

@yurii-kryvosheia  Could you share the version of kubecost you're running?

**Comment by michaelmdresser** [comment]
I defer to Neal, but I think this was fixed in https://github.com/kubecost/cost-analyzer-frontend/pull/1792 (coming in v1.101).

**Comment by yurii-kryvosheia** [comment]
> cc @nealormsbee @michaelmdresser
> 
> @yurii-kryvosheia Could you share the version of kubecost you're running?

Pardon me. Original post updated

**Comment by yurii-kryvosheia** [comment]
`v1.101.0-rc.4` seems fixed this error. The page loads fine 👌🏼

**Comment by teevans** [comment]
Thanks @yurii-kryvosheia! Going to go ahead and close this for now!
