### ISSUE TITLE
[Bug]  Aggregator pod crashes intermittently 

### ISSUE THREAD

**Issue by tabossert** [kubecost/cost-analyzer-helm-chart#3166]
### Kubecost Helm Chart Version

2.0.2

### Kubernetes Version

1.27

### Kubernetes Platform

AKS

### Description

Intermittently the kubecost pod restarts, due to an error in the aggregator pod as seen below

We have tuned resources as much as possible so it doesn't seem to be related to OOM or disk slowness.

### Steps to reproduce

1. Leave kubecost running in cluster, wait to see when it restarts

### Expected behavior

Pod would not be restarting

### Impact

Our scripts to pull data out fail when this happens

### Logs

```Shell
│ aggregator goroutine 1144450 [chan send]:                                                                                                                                                │
│ aggregator runtime.gopark(0x1?, 0xc06b7ec400?, 0x50?, 0x1?, 0x41?)                                                                                                                       │
│ aggregator     /usr/local/go/src/runtime/proc.go:398 +0xce fp=0xc052fd7d80 sp=0xc052fd7d60 pc=0x651cee                                                                                   │
│ aggregator runtime.chansend(0xc007491b60, 0xc052fd7f10, 0x1, 0xc01aa55f20?)                                                                                                              │
│ aggregator     /usr/local/go/src/runtime/chan.go:259 +0x3a5 fp=0xc052fd7df0 sp=0xc052fd7d80 pc=0x61c445                                                                                  │
│ aggregator runtime.chansend1(0x4e38c19?, 0x16?)                                                                                                                                          │
│ aggregator     /usr/local/go/src/runtime/chan.go:145 +0x17 fp=0xc052fd7e20 sp=0xc052fd7df0 pc=0x61c097                                                                                   │
│ aggregator github.com/kubecost/kubecost-cost-model/pkg/duckdb/allocation/db.(*AllocationDBQueryService).QueryAllocations.func1.1(0xc049aa7b80, {0xc049aa1600, 0xc, 0x10}, {0x80cab80, 0x │
│ aggregator     /app/kubecost-cost-model/pkg/duckdb/allocation/db/allocationqueryservice.go:1351 +0x2ee fp=0xc052fd7f58 sp=0xc052fd7e20 pc=0x2d9af6e                                      │
│ aggregator github.com/kubecost/kubecost-cost-model/pkg/duckdb/allocation/db.(*AllocationDBQueryService).QueryAllocations.func1.5()                                                       │
│ aggregator     /app/kubecost-cost-model/pkg/duckdb/allocation/db/allocationqueryservice.go:1380 +0x91 fp=0xc052fd7fe0 sp=0xc052fd7f58 pc=0x2d9ac31                                       │
│ aggregator runtime.goexit()                                                                                                                                                              │
│ aggregator     /usr/local/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc052fd7fe8 sp=0xc052fd7fe0 pc=0x684b81                                                                               │
│ aggregator created by github.com/kubecost/kubecost-cost-model/pkg/duckdb/allocation/db.(*AllocationDBQueryService).QueryAllocations.func1 in goroutine 796328                            │
│ aggregator     /app/kubecost-cost-model/pkg/duckdb/allocation/db/allocationqueryservice.go:1338 +0x377
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by AjayTripathy** [comment]
cc @cliffcolvin can you take a look here? Has this been fixed in the upcoming 2.1 rc's?
