### ISSUE TITLE
JS error: unrecognized expression in out of cluster costs

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#585]
APP VERSION: 1.61.3, SOURCE: /detail.html

Uncaught Error: Syntax error, unrecognized expression: #namespace-k8s.gcr.io/autoscaling-totalCost -- Error: Syntax error, unrecognized expression: #namespace-k8s.gcr.io/autoscaling-totalCost
at Function.oe.error (/jquery.min.3.3.1.js:2:12961)
at oe.tokenize (/jquery.min.3.3.1.js:2:18943)
at oe.select (/jquery.min.3.3.1.js:2:21833)
at Function.oe [as find] (/jquery.min.3.3.1.js:2:6808)
at w.fn.init.find (/jquery.min.3.3.1.js:2:24400)
at new w.fn.init (/jquery.min.3.3.1.js:2:24889)
at w (/jquery.min.3.3.1.js:2:896)
at updateStorageCost (/detail.html:1857:25)
at /detail.html:477:7
at Object.success (/detail.html:199:13)

**Comment by dwbrown2** [comment]
Able to reproduce... a regex is failing because of the `/` character.

**Comment by dwbrown2** [comment]
[PR](https://github.com/AjayTripathy/cost-analyzer-frontend/commit/832696c6579802f7522db20e0564ec45fed9396f) out for review in private frontend repo.

**Comment by dwbrown2** [comment]
Now resolved and in latest staging/nightly build. Expected in production early next week.
